### ISSUE TITLE
Add web interface like ESP32

### ISSUE THREAD

**Issue by trungthanh1288** [tesa-klebeband/RTL8720dn-WiFi-Packet-Injection#1]
First, this is a great work as i dont see any another RTL8720DN packet injection. I know this is base function only and it will broadcast deauth packet. Can you create a web interface to choise target and then based on selected target it will change Channel and mac of target to main loop ?

**Comment by tesa-klebeband** [comment]
Thank you very much for your compliment. I could make a web interface for the program, however this program was supposed to only be the base for other projects. Nevertheless, this is a good idea which I'll maybe try to implement in a while as I am currently pretty busy. If you want to, you could try doing this yourself by forking the repo, making your changes and opening a pull request which I will then merge.
