### ISSUE TITLE
It not deauth any SSID

### ISSUE THREAD

**Issue by trungthanh1288** [tesa-klebeband/RTL8720dn-WiFi-Packet-Injection#3]
Sorry for making another issues again, today im trying your code, uploaded to Ai-Thinker BW16 ( RTL8720DN), it running, created beacon but non SSID around is deauthed. I even try to put led control in loop to see if it running thought loop. Code is running, just not deauthen any thing

**Comment by tesa-klebeband** [comment]
If you post your code, I might be able to say what's wrong with it. You said that you can send beacon frames successfully right, so you can detect this ssid on your devices right? Also, did you call the WiFi ap setup function like I used it in my example code as it is required to send deauth frames. Another issue might be that you are using the wrong channel to deauth your devices. This would explain why sending and detecting beacons is possible but not deauthing as sending beacons is not channel specific but deauthing is. I hope I could help, if you send your code I will look over it. Have a great day!

**Comment by trungthanh1288** [comment]
> If you post your code, I might be able to say what's wrong with it. You said that you can send beacon frames successfully right, so you can detect this ssid on your devices right? Also, did you call the WiFi ap setup function like I used it in my example code as it is required to send deauth frames. Another issue might be that you are using the wrong channel to deauth your devices. This would explain why sending and detecting beacons is possible but not deauthing as sending beacons is not channel specific but deauthing is. I hope I could help, if you send your code I will look over it. Have a great day!

Hi, im using your example code and not change any thing yet, so you mean i have to change #define WIFI_CHANNEL to same channel of SSID i want to test the deauthen ? if so, its my bad as a was thought that WIFI_CHANNEL is only for AP beacon and your code will deauthe all SSID on all CHANNEL

**Comment by tesa-klebeband** [comment]
Yes, you need to change the channel to the channel of your example network. I maybe should have commented this in the code, thanks for pointing that out. I hope your code works now, good day!

**Comment by trungthanh1288** [comment]
> Yes, you need to change the channel to the channel of your example network. I maybe should have commented this in the code, thanks for pointing that out. I hope your code works now, good day!

Thank you for fast respone, i changed channel to same as my network, but it still not deauthe my devices. 
![image](https://github.com/tesa-klebeband/RTL8720dn-WiFi-Packet-Injection/assets/33550841/485bce08-cded-468f-8630-08b9233fabab)

The created beacon is on same Channel as i change too
![image](https://github.com/tesa-klebeband/RTL8720dn-WiFi-Packet-Injection/assets/33550841/a3e80202-6cf1-4baa-bbd1-fde756a48b22)

**Comment by tesa-klebeband** [comment]
Hi, from what I can see is that you didn't change the src Mac in the loop function to the Mac that your Network has which is {0xD4, 0x6D, 0x6D, 0xEB, 0xCD, 0x0F}. Just copy paste that into the declaration for src_mac and you should be good to go 👍🏻

**Comment by tesa-klebeband** [comment]
Hi, from what I can see is that you didn't change the src_mac declaration to the one your network you're trying to deauth has. If your network router has the Mac address of for example 12:34:56:78:90:ab the src_mac array should look like {0x12, 0x34, 0x56, 0x78, 0x90, 0xab}. You can find the Mac address of the network either in the router or in the windows settings. Hope this helps 👍🏻

**Comment by trungthanh1288** [comment]
> Hi, from what I can see is that you didn't change the src_mac declaration to the one your network you're trying to deauth has. If your network router has the Mac address of for example 12:34:56:78:90:ab the src_mac array should look like {0x12, 0x34, 0x56, 0x78, 0x90, 0xab}. You can find the Mac address of the network either in the router or in the windows settings. Hope this helps 👍🏻

Thank you. Its worked and deauthen my Device on channel 120. Just 0x12, 0x34, 0x56, 0x78, 0x90, 0xab is mac address from my device. We have to put BSSID of SSID we want to deauth which cost me some time to find it using another project for scan SSID's mac from https://github.com/alexus2033/RTL8720-Sniffer

**Comment by tesa-klebeband** [comment]
Glad it worked for you. I should probably write more documentation on the code. If you have any other questions feel free to open up another issue. Have a great day.
