### ISSUE TITLE
Idea for a project

### ISSUE THREAD

**Issue by PospelovDaniil** [tesa-klebeband/RTL8720dn-WiFi-Packet-Injection#4]
Hi, do you have enough knowledge to make firmware and board - 14 esp32 + N rtl8720 linked via SPI,
to experiment with 802.11 security (all channel sniffer, capture absolutely all PMKIDs, handshakes, write encrypted traffic to a SD card...).

I would do it myself, I'm actively working with 802.11, but I can't figure out how to link at least 2 esp32 in arduino ide over SPI with CRC data validation (even without CRC)...

**Comment by PospelovDaniil** [comment]
I would have done this a long time ago if I had a wrapper over SPI that had a trivial interface and good data rate,
for example 14 esp32's only could send packets, receive packets, change channel, change power and send all packets to the
"main esp32 (soon to be available esp32 P4 400Mhz)" which would already parse the packets (or each of the esp32 ?) ,
control which point to deauthenticate, which one to handshake or pmkid or write to SD card GPS tags with network data and signal strength...

**Comment by tesa-klebeband** [comment]
Hi, that is s great idea! I could try creating what your first comment suggests, but I don't have nearly as much esp32s and I am a bit busy with school right now. If you want to collaborate on such project with me, I would be interested in doing that.

**Comment by PospelovDaniil** [comment]
I'll text you on discord later.

**Comment by tesa-klebeband** [comment]
Sounds good!

**Comment by PospelovDaniil** [comment]
It's weird, but I can't find you on discord. - "tesa-klebeband#2004"
<img width="891" alt="image" src="https://github.com/tesa-klebeband/RTL8720dn-WiFi-Packet-Injection/assets/36377393/80a748ed-ddac-433f-90e7-7e3d6c693fb0">
<img width="885" alt="image" src="https://github.com/tesa-klebeband/RTL8720dn-WiFi-Packet-Injection/assets/36377393/d89e3314-11fc-4db7-9584-373a43a7c4ae">

You can message me on telegram @polonii210
Or try adding me as a friend on Discord yourself.
polonii210
<img width="150" alt="image" src="https://github.com/tesa-klebeband/RTL8720dn-WiFi-Packet-Injection/assets/36377393/4a557260-094f-4e7f-ad14-7de13ba87eb3">

**Comment by PospelovDaniil** [comment]
You probably don't have a check mark in your Discord settings for friendship requests - from everyone.
