### ISSUE TITLE
Code permission

### ISSUE THREAD

**Issue by Cancro29** [tesa-klebeband/RTL8720dn-WiFi-Packet-Injection#5]
Hello, I also developed a Wi-Fi penetration and social engineering software based on ESP8266 and ESP32. Just seeing this repo makes me incredibly happy because i don't have to wait for ESP32C5.

I want to ask, can I use your code in my project?

Please let met know.

Cancro29

**Comment by tesa-klebeband** [comment]
Hi! So great that you are actually asking. You can use my code in your project, but I would be really happy if you could give me credits for it. If you want to, I could contribute to the project you are working on too. Have a nice day

**Comment by Cancro29** [comment]
Thank you. I will credit you on my next BW16 based project.

Actually, I have a problem related to ESP32 that only can be fixed by modifying compiled libraries. If SoftAP is active and a station is connected to it, I cannot switch the Wi-Fi channel. This is a limitation from Espressif itself, presumably to prevent stations from getting disconnected. This limitation prevents me from deauthenticating multiple targets on different channels. However, in ESP8266 I can freely change Wi-Fi channels.

I hugely appreciate it if you can provide a solution to bypass that restriction, and I will credit you on the future project releases.

**Comment by tesa-klebeband** [comment]
Thank you! I can try looking into the esp32 precompiled libs in the next weeks. Have a nice day
